-- MySQL Script generated by MySQL Workbench
-- Tue Jun  6 10:08:31 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoas` (
  `ra` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `email` VARCHAR(100) NULL,
  `cpf` VARCHAR(15) NULL,
  `tipo` CHAR(1) NOT NULL,
  PRIMARY KEY (`ra`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ucs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ucs` (
  `iducs` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `ch` INT NULL,
  PRIMARY KEY (`iducs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`turmas` (
  `idturmas` INT NOT NULL AUTO_INCREMENT,
  `apelido` VARCHAR(45) NULL,
  `capacidade` VARCHAR(45) NULL,
  `turmascol` INT NULL,
  `ucs_iducs` INT NOT NULL,
  PRIMARY KEY (`idturmas`),
  INDEX `fk_turmas_ucs_idx` (`ucs_iducs` ASC),
  CONSTRAINT `fk_turmas_ucs`
    FOREIGN KEY (`ucs_iducs`)
    REFERENCES `mydb`.`ucs` (`iducs`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`pessoas_turmas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoas_turmas` (
  `ra` INT NOT NULL,
  `iidturmas` INT NOT NULL,
  `data` DATETIME NOT NULL,
  `ativo` TINYINT NULL DEFAULT 1,
  PRIMARY KEY (`ra`, `iidturmas`),
  INDEX `fk_pessoas_has_turmas_turmas1_idx` (`iidturmas` ASC),
  INDEX `fk_pessoas_has_turmas_pessoas1_idx` (`ra` ASC),
  CONSTRAINT `fk_pessoas_has_turmas_pessoas1`
    FOREIGN KEY (`ra`)
    REFERENCES `mydb`.`pessoas` (`ra`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pessoas_has_turmas_turmas1`
    FOREIGN KEY (`iidturmas`)
    REFERENCES `mydb`.`turmas` (`idturmas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
